%%{ init: { 'theme': 'dark' } }%%
graph TD

  Source_Files["Source_Files (3036 funcs)"]
  Expat["Expat (128 funcs)"]
  Extra_OpenGL_Docs["Extra OpenGL Docs (25 funcs)"]
  Extras["Extras (12 funcs)"]
  tools["tools (12 funcs)"]
  PBProjects["PBProjects (3 funcs)"]

  tools -->|4 calls| Source_Files

